package com.mutkuensert.fitnesspursuit.resources

object TextResourceKeys {
    const val APP_NAME = "app_name"
    const val ASK_WEIGHT = "ask_weight"
    const val CALCULATE = "calculate"
    const val WARMUP_SET_1_DESCRIPTION = "warmup_set_1_description"
    const val REP = "rep"
    const val REPS = "reps"
    const val WEIGHT_YOU_CAN_LIFT = "weight_you_can_lift"
    const val NUMBER_OF_REPS = "number_of_reps"
    const val ET_AL = "et_al"
    const val APP_BAR_MENU_BUTTON_DESCRIPTION = "app_bar_menu_button_description"
    const val CLOSE_NAVIGATION_MENU = "close_navigation_menu"
    const val APP_ICON_DESCRIPTION = "app_icon_description"
    const val BICEP = "bicep"
    const val LEFT = "left"
    const val RIGHT = "right"
    const val FOREARM = "forearm"
    const val CALF = "calf"
    const val CHEST = "chest"
    const val HIPS = "hips"
    const val NECK = "neck"
    const val SHOULDERS = "shoulders"
    const val THIGH = "thigh"
    const val SAVE = "save"
    const val WAIST = "waist"
    const val WARMUP_SETS = "warmup_sets"
    const val ONE_RM = "one_rm"
    const val BODY_SIZES = "body_sizes"
}