package com.mutkuensert.fitnesspursuit.resources

object TextResKeys {
    const val ADD_NEW = "add_new"
    const val APP_BAR_MENU_BUTTON_DESCRIPTION = "app_bar_menu_button_description"
    const val APP_ICON_DESCRIPTION = "app_icon_description"
    const val APP_NAME = "app_name"
    const val ASK_WORKOUT_WEIGHT = "ask_workout_weight"
    const val ATHLETE_NAME = "athlete_name"
    const val BICEP = "bicep"
    const val BODY_SIZES = "body_sizes"
    const val CALCULATE = "calculate"
    const val CALF = "calf"
    const val CHEST = "chest"
    const val CLOSE_NAVIGATION_MENU = "close_navigation_menu"
    const val ET_AL = "et_al"
    const val FOREARM = "forearm"
    const val HIPS = "hips"
    const val LEFT = "left"
    const val NECK = "neck"
    const val ONE_RM = "one_rm"
    const val REP = "rep"
    const val REPS = "reps"
    const val RIGHT = "right"
    const val SAVE = "save"
    const val SELECTED_ATHLETE_INFO_LR = "selected_athlete_info_lr"
    const val SET_CUSTOM_DATE_TIME = "set_custom_date_time"
    const val SHOULDERS = "shoulders"
    const val THIGH = "thigh"
    const val WAIST = "waist"
    const val WARMUP_SETS = "warmup_sets"
    const val WARMUP_SET_1_DESCRIPTION = "warmup_set_1_description"
    const val WEIGHT = "weight"
    const val KG = "kg"
}
